### ISSUE TITLE
add py 3.10 and remove 3.6

### ISSUE THREAD

**Issue by PhilipMay** [telekom/HPOflow#95]
## To-do

- [x] update Style Guidelines in `CONTRIBUTING.md`
- [x] update `python_requires` in `setup.py`
- [x] update `classifiers` in `setup.py`
- [x] update pytest GH action `python-version`
- [x] update `target-version` in `pyproject.toml`
- [x] add Release News in readme with description
- [x] make new release

**Comment by PhilipMay** [comment]
done
